services:
  db:
    image: postgres:16
    container_name: thatmoment_db
    environment:
      POSTGRES_DB: thatmoment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - thatmoment_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thatmoment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: thatmoment_redis
    ports:
      - "6379:6379"

  app:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: thatmoment_app
    working_dir: /workspace
    command: ./mvnw spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/thatmoment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      MAIL_HOST: mail.kurumsaleposta.com
      MAIL_PORT: 587
      MAIL_USERNAME: test@dippen.com.tr
      MAIL_PASSWORD: nuh7CotqUw9nat_hy
      MAIL_FROM: test@dippen.com.tr
      MAIL_FROM_NAME: That Moment
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace
      - ~/.m2:/root/.m2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  thatmoment_pgdata:
